---
# #####################################################################
# Deploy pod network
# #####################################################################
#
# Flannel
#
- name: Install flannel pod network
  block:
    - name: Flannel download kube-flannel.yml
      become: true
      become_user: ubuntu
      get_url:
        url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
        dest: /home/ubuntu/kube-flannel.yml
        mode: '0640'

    - name: CIDR
      debug:
        msg: "{{ pod_network_cidr }}"

    - name: Flannel adapt CIDR
      replace:
        path: /home/ubuntu/kube-flannel.yml
        regexp: '10.244.0.0/16'
        replace: "{{ pod_network_cidr }}"

    - name: Flannel install pod network
      become: true
      become_user: ubuntu
      command: kubectl apply -f /home/ubuntu/kube-flannel.yml
  when: cluster_networking == 'flannel_flannel'

#
# Calico for policy and networking
#
# https://docs.projectcalico.org/v3.10/getting-started/kubernetes/installation/calico
- name: Install calico pod network
  block:
    - name: Calico download calico.yml
      become: true
      become_user: ubuntu
      get_url:
        url: https://docs.projectcalico.org/v3.10/manifests/calico.yaml
        dest: /home/ubuntu/calico.yaml
        mode: '0640'

    - name: Calico adapt CIDR
      become: true
      become_user: ubuntu
      replace:
        path: /home/ubuntu/calico.yaml
        regexp: '192.168.0.0/16'
        replace: "{{ pod_network_cidr }}"

    # - name: Calico adapt MTU
    #   become: true
    #   become_user: ubuntu
    #   replace:
    #     path: /home/ubuntu/calico.yaml
    #     regexp: 'veth_mtu: "1440"'
    #     replace: 'veth_mtu: "1500"'

    - name: Calico install pod network
      become: true
      become_user: ubuntu
      command: kubectl apply -f /home/ubuntu/calico.yaml

    - name: Calico download calicoctl
      become: true
      get_url:
        url: https://github.com/projectcalico/calicoctl/releases/download/v3.5.8/calicoctl
        dest: /usr/local/bin/calicoctl
        mode: '0755'

    - name: Create /etc/calico
      become: true
      file:
        path: "/etc/calico"
        state: directory
        mode: '0755'

    - name: Create Calicoctl config
      copy:
        dest: /etc/calico/calicoctl.cfg
        mode: 0644
        content: |
          apiVersion: projectcalico.org/v3
          kind: CalicoAPIConfig
          metadata:
          spec:
            datastoreType: "kubernetes"
            kubeconfig: "/home/ubuntu/.kube/config"

    - name: Enable IP-in-IP Encapsulation
      become: true
      become_user: ubuntu
      shell: |
        calicoctl apply -f - << EOF
        apiVersion: projectcalico.org/v3
        kind: IPPool
        metadata:
          name: default-ipv4-ippool
        spec:
          cidr: {{ pod_network_cidr }}
          ipipMode: Always
          natOutgoing: true
        EOF
      args:
        chdir: $HOME

  when: cluster_networking == 'calico_calico'

#
# Calico for policy and flannel for networking
#
# https://docs.projectcalico.org/v3.7/getting-started/kubernetes/installation/flannel
- name: Install calico for policy and flannel for networking
  block:
    - name: Calico canal download canal.yml
      become: true
      become_user: ubuntu
      get_url:
        url: https://docs.projectcalico.org/v3.7/manifests/canal.yaml
        dest: /home/ubuntu/canal.yaml
        mode: '0640'

    - name: CIDR
      debug:
        msg: "{{ pod_network_cidr }}"

    - name: Calico canal adapt CIDR
      become: true
      become_user: ubuntu
      replace:
        path: /home/ubuntu/canal.yaml
        regexp: '10.244.0.0/16'
        replace: "{{ pod_network_cidr }}"

    - name: Calico canal install pod network
      become: true
      become_user: ubuntu
      command: kubectl apply -f /home/ubuntu/canal.yaml
  when: cluster_networking == 'calico_flannel'
