---
# #####################################################################
# Deploy Helm
# #####################################################################
- name: Helm download sources
  get_url:
    url: https://get.helm.sh/helm-v2.14.2-linux-amd64.tar.gz
    dest: /tmp

- name: Helm extract into /tmp
  unarchive:
    src: /tmp/helm-v2.14.2-linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Helm copy binary to /usr/local/bin
  copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin/helm
    remote_src: yes
    owner: root
    group: root
    mode: 0755

- name: Helm init
  become: true
  become_user: ubuntu
  command: helm init
  retries: 12
  delay: 10
  register: result
  until: result.rc == 0

- name: Helm create service account for tiller
  become: true
  become_user: ubuntu
  k8s:
    state: present
    definition:
      api_version: v1
      kind: serviceaccount
      metadata:
        name: tiller
        namespace: kube-system

- name: Helm create cluster role binding for tiller
  become: true
  become_user: ubuntu
  k8s:
    state: present
    definition:
      api_version: v1
      kind: ClusterRoleBinding
      metadata:
        name: tiller-cluster-role
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - kind: ServiceAccount
          name: tiller
          namespace: kube-system

# FIXME
#  --dry-run=true -o yaml | kubectl deploy -f -
- name: Helm configure tiller - step 1
  become: true
  become_user: ubuntu
  command: kubectl patch deploy --namespace kube-system tiller-deploy --patch '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'
  ignore_errors: yes

# FIXME
#  --dry-run=true -o yaml | kubectl deploy -f -
- name: Helm configure tiller - step 2
  become: true
  become_user: ubuntu
  command: kubectl -n kube-system patch deployment tiller-deploy -p '{"spec":{"template":{"spec":{"automountServiceAccountToken":true}}}}'
  ignore_errors: yes

- name: Helm bash command completion
  become: true
  become_user: ubuntu
  lineinfile:
    path: /home/ubuntu/.bashrc
    insertafter: EOF
    line: 'source <(helm completion bash)'
