---
# #####################################################################
# Create, Manage and Terminate a Kubernetes cluster with kubeadmin
# #####################################################################
- name: "Listing parameters"
  debug:
    msg:
      - "operation                    : {{ operation }}"

- name: Create Master
  include: k8s_create_master.yml
  when: operation == 'create_master'

- name: Create Workers
  include: k8s_create_workers.yml
  when: operation == 'create_workers'

- name: Create k8s certificate
  include: k8s_create_certificate.yml
  when: operation == 'k8s_create_certificate'

- name: Create k8s certificate pod
  include: k8s_create_certificate_pod.yml
  when: operation == 'k8s_create_certificate_pod'
