---
# #####################################################################
# Create, Manafe and Terminate PostgreSQL
# #####################################################################
- name: "Listing parameters"
  debug:
    msg:
      - "operation                    : {{ operation }}"

- name: Create instance
  include: psql_create_instance.yml
  when: operation == 'create_instance'

- name: Create database
  include: psql_create_database.yml
  when: operation == 'create_database'
