- hosts: tag_role_k8smaster
  vars:
  tasks:
    - name: Include vars
      include: site_vars.yml

    - name: Create Jenkins Credentials
      include_role:
        name: jenkins
      vars:
        operation: create_credentials
      when: site_deploy_jenkins == True
