- hosts: tag_role_k8smaster, tag_role_k8sworker
  vars:
  tasks:
    - name: Include vars
      include: site_vars.yml

    - name: Change Docker Socket Permissions
      become: true
      file:
        path: /var/run/docker.sock
        mode: '666'

    - name: Docker restart
      become: true
      command: systemctl reload docker
