- hosts: tag_role_k8smaster
  vars:
  tasks:
    - name: Include vars
      include: site_vars.yml

    - name: Get ipaddr of k8smaster
      set_fact:
        remote_ip: "{{ inventory_hostname | ipaddr}}"

    - name: Get ipaddr of k8smaster
      set_fact:
        remote_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
      when: not remote_ip

    - name: Store external ip address of kubernetes master
      add_host:
        name: "{{ remote_ip }}"
        groups: "moadsd_ng_k8smaster_instance_public"

- hosts: tag_role_k8smaster, tag_role_k8sworker
  vars:
  tasks:
    - name: Include vars
      include: site_vars.yml

    - name: Change Docker Socket Permissions
      become: true
      file:
        path: /var/run/docker.sock
        mode: '666'

    - name: Allow insecure registries
      become: true
      copy:
        dest: /etc/docker/daemon.json
        mode: 0640
        content: |
          {
            "insecure-registries": ["{{ groups['moadsd_ng_k8smaster_instance_public'][0] }}:{{ smartcheck_registry }}", "{{ groups['moadsd_ng_k8smaster_instance_public'][0] }}:{{ registry_nodeport }}", "{{ kubernetes_master_instance_name }}:{{ smartcheck_registry }}", "{{ kubernetes_master_instance_name }}:{{ registry_nodeport }}"]
          }

    - name: Docker restart
      become: true
      command: systemctl reload docker
