- hosts: all
  vars:
  tasks:
    - name: Include vars
      include: site_vars.yml

    - name: Stop instance
      include_role:
        name: environment-gcp
      vars:
        operation: stop_instance
      when: type == 'gcp'

    - name: Stop instance
      include_role:
        name: environment-aws
      vars:
        operation: stop_instance
      when: type == 'aws'

    - name: Stop instance
      include_role:
        name: environment-azure
      vars:
        operation: stop_instance
      when: type == 'azure'
