- hosts: tag_project_moadsd_ng
  gather_facts: false
  vars:
  tasks:
    - name: Include vars
      include: site_vars.yml

    - name: Stop instance
      include_role:
        name: environment-gcp
      vars:
        operation: stop_instance
        instance_name: "{{ hostvars[inventory_hostname]['name'] }}"
      when: type == 'gcp'

    - name: Stop instance
      debug:
        msg: "not yet implemented"
            # include_role:
      #   name: environment-aws
      # vars:
      #   operation: stop_instance
      #   instance_id: "{{ hostvars[inventory_hostname]['ec2_id'] }}"
      when: type == 'aws'

    - name: Stop instance
      debug:
        msg: "not yet implemented"
      # include_role:
      #   name: environment-azure
      # vars:
      #   operation: stop_instance
      when: type == 'azure'
