- hosts: all
  vars:
  tasks:
    - name: Include vars
      include: site_vars.yml

    - name: Start instance
      include_role:
        name: environment-gcp
      vars:
        operation: start_instance
        instance_name: "{{ hostvars[inventory_hostname]['ansible_nodename'] }}"
      when: type == 'gcp'

    - name: Stop instance
      include_role:
        name: environment-aws
      vars:
        operation: stop_instance
      when: type == 'aws'

    - name: Stop instance
      debug:
        msg: "not yet implemented"
      # include_role:
      #   name: environment-azure
      # vars:
      #   operation: stop_instance
      when: type == 'azure'
