---
# #####################################################################
# Create a network in GCP environment
# #####################################################################
- name: Current play
  debug:
    msg:
      - "Creating network {{ moadsd_ng_prefix }}-network"

- name: Create a network
  gcp_compute_network:
    name: "{{ moadsd_ng_prefix }}-network"
    auto_create_subnetworks: yes
    project: "{{ gcp_project_id }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_service_account_file }}"
    scopes: "{{ scopes }}"
    state: present
  register: network

- name: Create a firewall for ip-in-ip encapsulation
  gcp_compute_firewall:
    name: "{{ moadsd_ng_prefix }}-ipip-firewall"
    network:
      selfLink: "global/networks/{{ network.name }}"
    allowed:
      - ip_protocol: ipip
    source_tags:
      - "{{ gcp_project_id }}"
    project: "{{ gcp_project_id }}"
    priority: 1000
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_service_account_file }}"
    scopes: "{{ scopes }}"
    state: present
