---
# #####################################################################
# Stop an instance in GCP environment
# #####################################################################
- name: Current play
  debug:
    msg: "Stopping instance {{ instance_name }}"

- name: Stop instance
  delegate_to: 127.0.0.1
  command: gcloud compute instances stop --project "{{ gcp_project_id }}" --async "{{ instance_name }}" --zone "{{ gcp_zone }}" --quiet
