---
# #####################################################################
# Create a Jenkins instance
# #####################################################################
- name: Create Jenkins overrides file
  copy:
    dest: /home/ubuntu/overrides-jenkins.yml
    mode: 0640
    owner: ubuntu
    content: |
      master:
        image: {{ jenkins_image }}
        tag: {{ jenkins_tag }}
        adminUser: {{ admin_username }}
        adminPassword: {{ admin_password }}
        resources:
          limits:
            cpu: {{ limits_cpu }}
            memory: {{ limits_memory }}
        serviceType: {{ service_type }}
        nodePort: {{ service_port }}
        installPlugins:
          - kubernetes:1.18.2
          - workflow-job:2.33
          - workflow-aggregator:2.6
          - credentials-binding:1.19
          - git:3.11.0
          - kubernetes-cd:2.1.2
          - blueocean:1.19.0
          - locale:1.4
          - python:1.3
          # - deepsecurity-smartcheck-plugin:1.1.2
        scriptApproval:
          - "new groovy.json.JsonBuilder java.lang.Object"
          - "method groovy.lang.GroovyObject invokeMethod java.lang.String java.lang.Object"
      agent:
        image: "joao29a/jnlp-slave-alpine-docker"
        tag: "latest"
        envVars:
          - name: DSSC_REGISTRY
            value: {{ inventory_hostname }}:{{ smartcheck_registry }}
          - name: DSSC_SERVICE
            value: {{ inventory_hostname }}:{{ smartcheck_nodeport }}
          - name: K8S_REGISTRY
            value: {{ inventory_hostname }}:{{ registry_nodeport }}
        resources:
          limits:
            cpu: {{ agent_limits_cpu }}
            memory: {{ agent_limits_memory }}
        volumes:
          - type: HostPath
            hostPath: /var/run/docker.sock
            mountPath: /var/run/docker.sock
      persistence:
        StorageClass: {{ persistence_storageClassName }}
        size: {{ persistence_size }}
      rbac:
        create: {{ rbac_create }}

- name: Install Jenkins
  become: true
  become_user: ubuntu
  shell: helm install --namespace {{ jenkins_namespace }} --values overrides-jenkins.yml --name {{ jenkins_name }} {{ jenkins_chart }} --version {{ jenkins_chart_version }} >> jenkins.log
  args:
    chdir: $HOME
    creates: jenkins.log

- name: Fetch jenkins.log
  become: true
  become_user: ubuntu
  fetch:
    src: /home/ubuntu/jenkins.log
    dest: ./site_{{ type }}/
    flat: yes

- name: Store Jenkins credentials
  become: true
  become_user: ubuntu
  shell: |
    echo URL: http://{{ inventory_hostname }}:{{ jenkins_nodeport }} > jenkins.txt
    echo Username: admin >> jenkins.txt
    echo Password: $(kubectl get secret --namespace jenkins jenkins -o jsonpath="{.data.jenkins-admin-password}" | base64 --decode) >> jenkins.txt
  args:
    chdir: $HOME
    creates: jenkins.txt

- name: Fetch jenkins.txt
  become: true
  become_user: ubuntu
  fetch:
    src: /home/ubuntu/jenkins.txt
    dest: ./site_{{ type }}/
    flat: yes
