---
# #####################################################################
# Create, Manage and Terminate Jenkins
# #####################################################################
- name: "Listing parameters"
  debug:
    msg:
      - "operation                    : {{ operation }}"

- name: Create instance
  include: jenkins_create_instance.yml
  when: operation == 'create_instance'

- name: Create credentials
  include: jenkins_create_credentials.yml
  when: operation == 'create_credentials'
