# #####################################################################
# Create, Manafe and Terminate GCP environment
# #####################################################################
---
- name: "Listing parameters"
  debug:
    msg:
      - "operation                    : {{ operation }}"

- name: Create linux instance
  include: esx_create_linux_instance.yml
  when: operation == 'create_linux_instance'

# - name: Terminate instance
#   include: esx_terminate_instance.yml
#   when: operation == 'terminate_instance'
